inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*

Layout/LineLength:
  Max: 140

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
