---
services: docker
dist: bionic
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
script:
  - 'bundle exec rails $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.7.1
    bundler_args: --without development --jobs "$(nproc)"
    env: CHECK=rubocop
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
